### ISSUE TITLE
1.1 - Personal Website - Holly Goen

### ISSUE THREAD

**Issue by techgravy** [TIY-GVL-FEE-2015-August/assignments#15]
### Tasks

* [x] Create a new Issue with these tasks!
* [x] Use the Github app to create a  repository `1.1-Personal-Website`
* [x] Create your personal website
    * [x] Checkpoint: Created and committed `index.html`
    * [x] Checkpoint: Created and committed `main.css`
    * [x] Complete: Pushed `index.html` and `main.css`

**Comment by techgravy** [comment]
https://github.com/techgravy/1.1-personal-website

Level 3
Took about an hour total
Its not going to win any awards, but it works.

**Comment by jacobthemyth** [comment]
https://dl.dropboxusercontent.com/spa/71j5qnsbba975h8/fd6cb78w.png

:smile:
