### ISSUE TITLE
5.1-Create A Gulpfile-Tyler Reckart

### ISSUE THREAD

**Issue by tylerreckart** [TIY-GVL-FEE-2015-August/assignments#206]
### Requirements

- [x] Read [Gulp for Beginners](https://css-tricks.com/gulp-for-beginners/), creating the `gulpfile.js` file as you work through the reading.
- [x] Create a repository on GitHub called `frontend-scaffolding` containing the results of this exercise.

**Comment by tylerreckart** [comment]
https://github.com/tylerreckart/sassafras

Time to complete: >1 hour
Learning zone: 2
Results: I've actually been working with gulp for a few weeks to build my own compiling tool, so I'm pretty comfortable with it right now. I attached the repo that I've been working with since it goes above and beyond the tutorial

**Comment by jacobthemyth** [comment]
Ha yeah I noticed that a while ago and I meant to mention that you probably didn't need to go through the tutorial, but hopefully you still learned a thing or two :)
