### ISSUE TITLE
1.1-Personal Website- Tyler A. Reckart

### ISSUE THREAD

**Issue by tylerreckart** [TIY-GVL-FEE-2015-August/assignments#23]
### Tasks

* [x] Create a new Issue with these tasks!
* [x] Use the Github app to create a  repository `1.1-Personal-Website`
* [x] Create your personal website
    * [x] Checkpoint: Created and committed `index.html`
    * [x] Checkpoint: Created and committed `main.css`
    * [x] Complete: Pushed `index.html` and `main.css`

**Comment by tylerreckart** [comment]
https://github.com/tylerreckart/1.1-personal-website

Learning Zone: 2
Time: 2 hours
Results: Finished and happy with the overall styling and animation

**Comment by tylerreckart** [comment]
Here's the blog post for today's assignment: https://medium.com/the-iron-yard/day-one-970e2386314a

**Comment by joeygaskin** [comment]
Dude this looks awesome!! Great job!
