### ISSUE TITLE
1.1 - Personal Website - Joey Gaskin

### ISSUE THREAD

**Issue by joeygaskin** [TIY-GVL-FEE-2015-August/assignments#30]
Tasks

* [x] Create a new Issue with these tasks!
* [x] Use the Github app to create a  repository `1.1-Personal-Website`
* [x] Create your personal website
    * [x] Checkpoint: Created and committed `index.html`
    * [x] Checkpoint: Created and committed `main.css`
    * [x] Complete: Pushed `index.html` and `main.css`

**Comment by joeygaskin** [comment]
https://github.com/joeygaskin/1.1-Personal-Website
Learning Zone: 1
Time: 30 min.
Result: Finished tasks. Had difficulty using and navigating in GitHub and Git.

**Comment by tylerreckart** [comment]
Thanks man! You're site looks great too!

**Comment by joeygaskin** [comment]
http://joeygaskin.github.io/1.1-Personal-Website
