### ISSUE TITLE
1.2 - Blog Layout - Joey Gaskin

### ISSUE THREAD

**Issue by joeygaskin** [TIY-GVL-FEE-2015-August/assignments#34]
https://github.com/joeygaskin/1.2-blog-layout

**Comment by joeygaskin** [comment]
<b>Normal Mode</b> 
Learning Zone: 2.5
Time: 3 hours
Results: Finished. It took a moment of tinkering with it, but I eventually figured it out.

**Comment by jacobthemyth** [comment]
This assignment was supposed to be deployed to GitHub Pages, but no big deal, I was able to download it. Let me know if you need help publishing it in the future. :+1:
