### ISSUE TITLE
1.2 Blog-Layout-Richard Freeman

### ISSUE THREAD

**Issue by rfree86** [TIY-GVL-FEE-2015-August/assignments#38]
- a git repo containing:
    - `index.html`
    - `styles` folder
        - `style.css`
    - `images` folder
        - with any images you used with your design

**Comment by rfree86** [comment]
https://github.com/rfree86/1.2-Blog-Layout.git
 
Normal Mode
Time: 7hrs
comfort level: 4
Results: Finished but overall not happy with final product.  I struggled with the spacing throughout and could not get the font and some other details to work for me.

**Comment by jacobthemyth** [comment]
Great work, I wouldn't worry about the fonts and things, this was more to practice layout.
