### ISSUE TITLE
1.3 Timeline Layout

### ISSUE THREAD

**Issue by krutpatel9** [TIY-GVL-FEE-2015-August/assignments#58]
* **Write Some Code**
    * [ ] Checkpoint: Initial commit!
    * [x] Checkpoint: Basic page structure (HTML only)!
    * [x] Checkpoint: First line of CSS committed and pushed!
    * [x] Checkpoint: Two column layout achieved.
    * [ ] Checkpoint: Colors are exactly right.
    * [x] Checkpoint: Icons in place.
    * [x] Checkpoint: Circles and lines finished.
    * [x] Checkpoint: Hover states and transitions are done. Fancy.
    * [x] Mission Complete

**Comment by jacobthemyth** [comment]
Don't forget to comment with your summary and URL. If you want to run through this sometime, just let me know :)
